import { TrackItem } from './tracks.types';

const previewUrls = [
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
];

const cover = (seed: number) =>
  `https://loremflickr.com/800/800/music?lock=${seed}`;

const baseTracks = [
  ['Neon Run', 'HAT', 'Pop', 'Happy', 'Vlog', 'Vocal', 'English', 'High', 29, 118, 24, 'Standard'],
  ['Midnight Chase', 'DEN', 'Cinematic', 'Dark', 'Movie Recap', 'Instrumental', 'Instrumental', 'High', 64, 132, 39, 'Extended'],
  ['Coffee Shop Rain', 'Luna', 'Lofi', 'Chill', 'Podcast', 'Instrumental', 'Instrumental', 'Low', 58, 82, 18, 'Standard'],
  ['Summer Flashback', 'Minh Anh', 'Pop', 'Happy', 'Travel Vlog', 'Vocal', 'Vietnamese', 'Medium', 34, 110, 21, 'Standard'],
  ['Epic Uprising', 'Atlas', 'Cinematic', 'Epic', 'Trailer', 'Instrumental', 'Instrumental', 'High', 76, 140, 49, 'Extended'],
  ['Broken Streetlights', 'Ryn', 'Ballad', 'Sad', 'Storytelling', 'Vocal', 'English', 'Low', 43, 74, 16, 'Standard'],
  ['Skyline Drift', 'Nova', 'EDM', 'Energetic', 'Gaming', 'Instrumental', 'Instrumental', 'High', 61, 128, 32, 'Extended'],
  ['Golden Hours', 'Tia', 'Acoustic', 'Warm', 'Lifestyle', 'Vocal', 'English', 'Medium', 47, 92, 19, 'Standard'],
  ['Late Night Typebeat', 'Producer A', 'Rap', 'Dark', 'Shorts', 'Instrumental', 'Instrumental', 'Medium', 52, 96, 27, 'Standard'],
  ['Ocean Postcard', 'Ari', 'Indie', 'Chill', 'Travel Vlog', 'Vocal', 'English', 'Medium', 55, 88, 23, 'Standard'],
  ['Pulse of Victory', 'Kai', 'EDM', 'Epic', 'Sports', 'Instrumental', 'Instrumental', 'High', 69, 150, 44, 'Extended'],
  ['Quiet Letters', 'Emi', 'Ballad', 'Sad', 'Drama', 'Vocal', 'Japanese', 'Low', 41, 70, 17, 'Standard'],
  ['City Pop Signal', 'Mika', 'Pop', 'Happy', 'Commercial', 'Vocal', 'Japanese', 'Medium', 33, 116, 26, 'Extended'],
  ['Dark Mode Trailer', 'Orion', 'Cinematic', 'Dark', 'Trailer', 'Instrumental', 'Instrumental', 'High', 74, 136, 52, 'Exclusive'],
  ['Sunset Reels', 'Lyn', 'Acoustic', 'Warm', 'Reels', 'Vocal', 'Vietnamese', 'Medium', 28, 104, 15, 'Standard'],
  ['Glitch Horizon', 'Zero8', 'EDM', 'Energetic', 'Tech Review', 'Instrumental', 'Instrumental', 'High', 63, 144, 37, 'Extended'],
  ['Soft Bloom', 'Nhi', 'Lofi', 'Chill', 'Beauty', 'Instrumental', 'Instrumental', 'Low', 46, 78, 14, 'Standard'],
  ['Truth in Motion', 'Levi', 'Rap', 'Bold', 'Ads', 'Vocal', 'English', 'High', 57, 98, 31, 'Extended'],
  ['Crystal Dawn', 'Sena', 'Indie', 'Dreamy', 'Fashion', 'Vocal', 'Korean', 'Medium', 49, 90, 22, 'Standard'],
  ['Monsoon Memory', 'Vy', 'Ballad', 'Sad', 'AI Storytelling', 'Vocal', 'Vietnamese', 'Low', 62, 72, 20, 'Standard'],
] as const;

export const mockTracks: TrackItem[] = baseTracks.map((item, index) => {
  const [
    title,
    artistName,
    genre,
    mood,
    useCase,
    vocalType,
    language,
    energyLevel,
    duration,
    bpm,
    price,
    licenseType,
  ] = item;

  const createdAt = `2026-05-${String((index % 20) + 1).padStart(2, '0')}T08:00:00Z`;
  const publishedAt = `2026-05-${String((index % 20) + 1).padStart(2, '0')}T10:00:00Z`;
  const verified = index % 5 !== 0;

  return {
    id: `track-${index + 1}`,
    asset_id: `AST-${String(index + 1).padStart(4, '0')}`,
    title,
    artist_name: artistName,
    composer: `${artistName} Composer`,
    publisher: 'Solo Coder Music',
    description: `${title} is a demo-ready ${genre.toLowerCase()} track tailored for ${useCase.toLowerCase()} content and short-form creator workflows.`,
    release_date: `2025-${String((index % 12) + 1).padStart(2, '0')}-15`,
    cover_image_url: cover(index + 1),
    file_url: `https://cdn.example.com/audio/original/${index + 1}.mp3`,
    file_type: 'mp3',
    bitrate: 320,
    sample_rate: 44100,
    duration,
    bpm,
    key: ['C Major', 'A Minor', 'D Minor', 'G Major', 'F Major'][index % 5],
    file_size_mb: Number((duration / 8).toFixed(1)),
    mood: [mood],
    genre: [genre],
    energy_level: energyLevel,
    use_case: [useCase],
    vocal_type: vocalType as 'Vocal' | 'Instrumental',
    language,
    theme: [mood, useCase],
    rights_holder: `${artistName} Rights LLC`,
    ownership_type: index % 4 === 0 ? 'publishing' : 'master',
    copyright_status: verified ? 'registered' : 'unregistered',
    licensing_available: true,
    commercial_allowed: index % 6 !== 0,
    allowed_platforms: ['YouTube', 'TikTok', 'Reels', 'Shorts'],
    territory: 'Worldwide',
    expiration: null,
    upload_date: createdAt,
    uploaded_by: 'admin-demo',
    asset_status: 'active',
    verification_status: verified ? 'verified' : 'pending',
    preview_url: previewUrls[index % previewUrls.length],
    preview_duration: 30,
    price,
    currency: 'USD',
    license_type: licenseType as 'Standard' | 'Extended' | 'Exclusive',
    trending_score: 100 - index * 3,
    download_count: 500 - index * 11,
    monetization_allowed: index % 3 !== 0,
    commercial_usage_allowed: index % 6 !== 0,
    sponsor_usage_allowed: index % 4 !== 0,
    ads_usage_allowed: index % 5 !== 0,
    personal_usage_allowed: true,
    youtube_allowed: true,
    youtube_shorts_allowed: index % 4 !== 1,
    youtube_long_form_allowed: true,
    platform_scope_note: 'Applies to creator content on supported video platforms',
    certification_id: `MSC-2026-${String(index + 1).padStart(4, '0')}`,
    certification_status: verified ? 'Certified' : 'Pending',
    certification_scope: 'YouTube Monetization',
    content_id_safe_declaration: verified,
    certified_by: 'admin-demo',
    certified_at: publishedAt,
    certificate_valid_from: publishedAt,
    certificate_valid_until: null,
    verification_id: `VER-${String(index + 1).padStart(4, '0')}`,
    reviewed_by_admin_id: 'admin-demo',
    reviewed_at: publishedAt,
    rejection_reason: null,
    admin_note: verified ? 'Verified for demo marketplace' : 'Awaiting final review',
    status: 'published',
    visibility: 'public',
    created_at: createdAt,
    updated_at: publishedAt,
    published_at: publishedAt,
    archive_status: false,
    deleted_at: null,
  };
});
